CREATE TABLE IF NOT EXISTS Boss (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Department (
	id SERIAL PRIMARY KEY,
	department VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Employee (
	id SERIAL PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
    boss_id INTEGER REFERENCES Boss(id),
    department_id INTEGER REFERENCES Department(id)
);